// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE87ILs-ptG0Ij4T9-ydDww0sTBqF-L8A',
    appId: '1:737008980753:web:2be084e22fc7fc59f6f2b0',
    messagingSenderId: '737008980753',
    projectId: 'hale-54ebc',
    authDomain: 'hale-54ebc.firebaseapp.com',
    storageBucket: 'hale-54ebc.appspot.com',
    measurementId: 'G-9QP8ZLPWVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF2PqTsiDkOsjYJVjoNhlRq_8TbWPVrrQ',
    appId: '1:737008980753:android:89d19b1a38c2ac72f6f2b0',
    messagingSenderId: '737008980753',
    projectId: 'hale-54ebc',
    storageBucket: 'hale-54ebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc5eIRFz9PmGp_2lXALSe05jVVxUzOYYo',
    appId: '1:737008980753:ios:d44a1958bd5074a8f6f2b0',
    messagingSenderId: '737008980753',
    projectId: 'hale-54ebc',
    storageBucket: 'hale-54ebc.appspot.com',
    iosBundleId: 'com.example.hale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc5eIRFz9PmGp_2lXALSe05jVVxUzOYYo',
    appId: '1:737008980753:ios:42600ba0dc034432f6f2b0',
    messagingSenderId: '737008980753',
    projectId: 'hale-54ebc',
    storageBucket: 'hale-54ebc.appspot.com',
    iosBundleId: 'com.example.hale.RunnerTests',
  );
}
